name: Image Build CI

on:
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t labstrap .
    - name: Get base image
      run: wget -O ~/input.tar.zst http://download.proxmox.com/images/system/ubuntu-22.04-standard_22.04-1_amd64.tar.zst
    - name: Build it!
      run: |
        docker run --rm -i --name=labstrap --privileged \
        -v "$PWD":/srv:ro \
        -v $HOME/rootfs:/target \
        -v $HOME/input.tar.zst:/input.tar.zst:ro \
        labstrap
    - name: Pack it!
      run: |
        sudo tar caf output.tar.zst -C $HOME/rootfs .
        sha256sum output.tar.zst > sha256.txt
        echo "SHA256: $(<sha256.txt)" > ${{ github.workspace }}/release-info.txt
    - name: Upload it!
      uses: softprops/action-gh-release@v1
      with:
        name: Auto build from GitHub Actions run ${{ github.run_number }}
        body_path: ${{ github.workspace }}/release-info.txt
        files: |
          output.tar.zst
          sha256.txt
